update to PyBank and PyPoll
writing csv file for data and questions to consider moving fwd:
1.) can this method be simplified, as in how to add all this data at once instead of performing individual lines
2.) both codes perform fine on the interactive interface, but do not work without the #%%, it says that this "File "<stdin>", line 1" and then " ^
SyntaxError: invalid syntax" which I do not understand. Will ask about during office hours/brain storm with peers